-- ============================================
-- SCHEMA DATABASE SUPABASE
-- Portal Kelurahan Kakaskasen Dua
-- ============================================

-- Tabel Laporan Warga
-- Jalankan SQL ini di Supabase SQL Editor
-- Dashboard → SQL Editor → New Query → Paste → Run

CREATE TABLE IF NOT EXISTS laporan (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_pelapor    TEXT NOT NULL,
  no_telepon      TEXT,
  email           TEXT,
  alamat          TEXT,
  kategori        TEXT NOT NULL,
  judul           TEXT NOT NULL,
  deskripsi       TEXT NOT NULL,
  lokasi_kejadian TEXT,
  status          TEXT DEFAULT 'Diterima' CHECK (status IN ('Diterima', 'Diproses', 'Selesai', 'Ditolak')),
  catatan_admin   TEXT,
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  updated_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Index untuk query yang sering digunakan
CREATE INDEX IF NOT EXISTS idx_laporan_kategori ON laporan (kategori);
CREATE INDEX IF NOT EXISTS idx_laporan_status ON laporan (status);
CREATE INDEX IF NOT EXISTS idx_laporan_created_at ON laporan (created_at DESC);

-- Enable Row Level Security (RLS)
ALTER TABLE laporan ENABLE ROW LEVEL SECURITY;

-- Policy: Siapa saja bisa INSERT (membuat laporan baru)
CREATE POLICY "Allow public insert"
  ON laporan
  FOR INSERT
  TO anon
  WITH CHECK (true);

-- Policy: Hanya authenticated users (admin) bisa SELECT, UPDATE, DELETE
CREATE POLICY "Allow authenticated read"
  ON laporan
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Allow authenticated update"
  ON laporan
  FOR UPDATE
  TO authenticated
  USING (true);

CREATE POLICY "Allow authenticated delete"
  ON laporan
  FOR DELETE
  TO authenticated
  USING (true);

-- Trigger untuk auto-update updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at
  BEFORE UPDATE ON laporan
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- SELESAI!
-- ============================================
-- Setelah menjalankan SQL ini:
-- 1. Buka Settings → API di Supabase Dashboard
-- 2. Copy "Project URL" → masukkan ke NEXT_PUBLIC_SUPABASE_URL di .env.local
-- 3. Copy "anon public" key → masukkan ke NEXT_PUBLIC_SUPABASE_ANON_KEY di .env.local
-- 4. Restart dev server (npm run dev)
